server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Reggie
    username: john
    password: csh020329@
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: '/Users/chengshenghan/Desktop/reggie_images/'